version: "2"
services:
  app:
    image: serafinlabs/nodejs:10-dev
    command: "npm run-script dev"
    ports:
      - "80:80"
      - "9229:9229"
    volumes:
      - .:/srv
      - ~/.ssh/id_rsa:/home/node/.ssh/id_rsa:ro
  swagger:
    image: swaggerapi/swagger-ui
    links:
      - app
    ports:
      - "8082:8080"
    environment:
      API_URL: http://localhost/api.json
  swagger-editor:
    image: swaggerapi/swagger-editor:latest
    ports:
      - "8081:8080"